#!/usr/bin/env bash
# this is a comment

if [ $1 == "holberton.online" ];
then
  echo -e  "The subdomain www is a A record and points to 54.210.47.110
The subdomain lb-01 is a A record and points to 54.210.47.110
The subdomain web-01 is a A record and points to 34.198.248.145
The subdomain web-02 is a A record and points to 54.89.38.100"
else
  echo -e "The subdomain www is a A record and points to 54.210.47.110"
fi