#!/usr/bin/env bash
# comment
hour=0
min=1
while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    while [ $min -le 59 ]; do
	echo "$min"
	min=$(( min + 1 ))
    done
    min=1
    hour=$(( hour + 1))
done
